"use client";

import { Button } from "@/components/ui/button";
import { useAuthLogout } from "@/lib/client/hooks/use-auth-logout";
import { useAuthSession } from "@/lib/client/hooks/use-auth-session";
import Head from "next/head";

export default function Dashbaord() {
  const session = useAuthSession();
  const logout = useAuthLogout();
  console.log({ session });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {session.email}
        <br />
        {session.userId}

        <Button onClick={() => logout.mutate()}>Logout</Button>
      </main>
    </>
  );
}
