"use client";

import { Skeleton } from "@/components/ui/skeleton";
import { useAuthSession } from "@/lib/client/hooks/use-auth-session";
import Head from "next/head";

export default function Dashbaord() {
  const session = useAuthSession();
  console.log({ session });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Skeleton className="m-4 w-full" />
    </>
  );
}
